# Generated by Django 4.1.3 on 2023-01-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postmodel_delete_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
