# Generated by Django 4.1.3 on 2023-01-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
