# Generated by Django 4.1.3 on 2023-01-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_postmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
