# Generated by Django 4.1.3 on 2023-01-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='myPosts'),
        ),
    ]
