# Generated by Django 4.1.3 on 2023-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_postmodel_comment_count_postmodel_likers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to='myPosts')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='likers',
        ),
    ]
